language: node_js
node_js: 12
install:
  - npm install
script:
  - npm run lint
  - npm run test
  - npm run build
after_success:
  - npx semantic-release
  - npm run coveralls
env:
  global:
    - secure: lycL1urR9Q+jEe0w08WqjLxoaif+4xPJF5LY30zQrpR2Vr4MYAlqfY390Z4HQta7Ml6VYCDpolEeZB/Am9msVlh6TOqvXkEZqXcAEnrnrKpww+nAmESL2eZ5Nmnh6KsfcWEu6J5SLipQSJm3pdmXK4KrXavcIRLo5WPDyo5lfC1sevvtW5Byhx2XBN2zij8wwr/n5bddlAGwt/xL2levAT8qjPcXHYu4jM1u1iWk/0rM9NkrVvSvdA2c33DKxgNe8FvVOMxcryVgQtgmdq/Shjo5Gwbvzl/BzX+HASWNuWoDJ1RMn1257rHyusEvx/RISQEh5ApdY9nU5NF0w92ZPdVzvMa1Ahu5PMOBD3oPtfhETeHXJY5abuKx3Z+06QJUSOuzIKiBJA1xf2diA1CeWV7t0qD8EiXiWqDODG5t5N94iZi19pN29ErWVj/j/2q8LyAfTkzy6108Hnw8ioYVCJu08nuSp0DWdZ5uQcv8tVFdvcPAOGw+T2uh6DRnkNaotZcX4fkIUelprDqNpayw+YMMXPQTF5if4st63jJo+8+yNmd9ec2fkDBZMGn61Ul/D+rUgLPB6hykU5ddxtfS3DTWxBfTh74Oy8X3WITi311YkjVjdcB2Y3PfijQL6Q3D+4pZVKnXx3FWDOvciZZ0pEBUdsuUkE4uASCfwKhV2xw=
    - secure: QP5UiAiSVWawu7gaDLMKOTwRePIWubaCxsXg6in2wSXLrtPa6eCY/Kwmz3RRjH0Irkf2Pp42lEJuWZqW53UDDJrt/TGyDJKDsXMHVVQPwNO6D+bH6/0oAghVbYVJQF2aMXZ45PpDsw0NqVlTs2bTv5Ui2e8OLP2fdNrXaGGV7DT2i9dN6x1WQ8kpJFlrtNvusb+OuVyUWgbHgAnLXOH/Uj7YMQbewJiwXd/kVoOrCZ/MKa7Vo/yWa6ajJIXKgqkGNgt2MmUdynxy2LbuMcYg95AMNTpD4YzQYYX7C74UKy6mMjc8NG08sYw6wG082KkpqvXfw28qE1Rzgymg4t3AQmIDwcPpejDIeELW+3ePHU3oS23DnBGzWabakpmdyCoNp6/NR2Mojicijk86Sb3oyrr9FbVwoZqkMAYqtcILnhDepPKUOO2RDMaFxkC3BjVDe+TDQx/5m0q96e01W1F9fKF7xKNFFKQrrw7hO2ZhPrSLb24qKpASVhM5QITSoWbCZyRtlEQLOboggdDwWd4GGTuf5cy+CAFIWaR33uvJLOIF8HXbBNocnH7wwifwFaH0sXQEaS0zxZkB/sTw4Za7xKPFcNuwyJmffFS8zob32fcrSg2qHG03bGb6z7iRaN3zAvitKJPlhmsmV8j4djbOrj0iP0x7dsbBDGqVhgrjGLI=
